update g0vernance content
g0v/landing-page pull request #40
Opened 2024-08-12 06:23 UTC by SeanGau

根據討論共筆 https://g0v.hackmd.io/Ki8oBtnjTjitnyp84ckYbA 新增社群共識內容
黑底文字是使用 g0vernance 頁面的大白話樣式，hover 時才會顯示

![image](https://github.com/user-attachments/assets/1c566978-0b84-4ce6-83c4-fe480b87083f)

2024-08-12 08:43 UTC, rschiang reviewed
覺得這邊比較重要的字如果用空的 `<li>` 做 hover 效果會有網頁無障礙的問題。但也是可以先 merge 再慢慢改！owo)

2024-08-12 08:47 UTC, rschiang requested changes
抓到了一點 CSS 的 bug！有多一個 `line`

2024-08-12 08:47 UTC, rschiang commented on web/src/styl/index.styl
> +  line
這邊這個是有什麼特殊的意義嗎，還是寫錯了XD

2024-08-13 05:07 UTC, SeanGau commented on web/src/styl/index.styl
> +  line
漏刪XD

2024-08-13 05:20 UTC, SeanGau commented
的確...無障礙的部分要改的滿多的，也許之後採用透明文字的方式？

> 覺得這邊比較重要的字如果用空的 `<li>` 做 hover 效果會有網頁無障礙的問題。但也是可以先 merge 再慢慢改！owo)

2024-08-13 07:59 UTC, merged

2024-08-13 08:00 UTC, rschiang commented
@SeanGau 欸我發現你沒有 rebuild CSS XDDDD
他會自己處理嗎？

2024-08-13 08:03 UTC, SeanGau commented
> @SeanGau 欸我發現你沒有 rebuild CSS XDDDD
> 他會自己處理嗎？

Deploy 的時候會再 rebuild~~ 這些都應該要加進 gitignore